const productsAndServices = [
	{
		productId: "901",
		productLogo: "https://caerwyns-creations.s3.us-west-2.amazonaws.com/Aztec.jpg",
		productLogoAlt: "Aztec Bracelet",
		productName: "Aztec Bracelet",
		productColor: "red",
		productRowHeader: "",
		productCardHeader: "",
		productIncludes1: "",
		productIncludes2: "",
		productIncludes3: "",
		productButtonText1: "Fast Checkout",
		productButtonText2: "Add to Cart",
		productPrice: "$2.00"
	},
	{
		productId: "902",
		productLogo: "https://caerwyns-creations.s3.us-west-2.amazonaws.com/Brave.jpg",
		productLogoAlt: "Brave Bracelet",
		productName: "Brave Bracelet",
		productColor: "red",
		productRowHeader: "",
		productCardHeader: "",
		productIncludes1: "",
		productIncludes2: "",
		productIncludes3: "",
		productButtonText1: "Fast Checkout",
		productButtonText2: "Add to Cart",
		productPrice: "$2.00"
	},
	{
		productId: "903",
		productLogo: "https://caerwyns-creations.s3.us-west-2.amazonaws.com/Calm.jpg",
		productLogoAlt: "Calm Bracelet",
		productName: "Calm Bracelet",
		productColor: "red",
		productRowHeader: "",
		productCardHeader: "",
		productIncludes1: "",
		productIncludes2: "",
		productIncludes3: "",
		productButtonText1: "Fast Checkout",
		productButtonText2: "Add to Cart",
		productPrice: "$2.00"
	},
	{
		productId: "904",
		productLogo: "https://caerwyns-creations.s3.us-west-2.amazonaws.com/Canyon.jpg",
		productLogoAlt: "Canyon Bracelet",
		productName: "Canyon Bracelet",
		productColor: "red",
		productRowHeader: "",
		productCardHeader: "",
		productIncludes1: "",
		productIncludes2: "",
		productIncludes3: "",
		productButtonText1: "Fast Checkout",
		productButtonText2: "Add to Cart",
		productPrice: "$2.00"
	},
	{
		productId: "905",
		productLogo: "https://caerwyns-creations.s3.us-west-2.amazonaws.com/Luna.jpg",
		productLogoAlt: "Luna Bracelet",
		productName: "Luna Bracelet",
		productColor: "blue",
		productRowHeader: "",
		productCardHeader: "",
		productIncludes1: "",
		productIncludes2: "",
		productIncludes3: "",
		productButtonText1: "Fast Checkout",
		productButtonText2: "Add to Cart",
		productPrice: "$2.00"
	},
	{
		productId: "906",
		productLogo: "https://caerwyns-creations.s3.us-west-2.amazonaws.com/Mermaid.jpg",
		productLogoAlt: "Mermaid Bracelet",
		productName: "Mermaid Bracelet",
		productColor: "red",
		productRowHeader: "",
		productCardHeader: "",
		productIncludes1: "",
		productIncludes2: "",
		productIncludes3: "",
		productButtonText1: "Fast Checkout",
		productButtonText2: "Add to Cart",
		productPrice: "$2.00"
	},
	{
		productId: "907",
		productLogo: "https://caerwyns-creations.s3.us-west-2.amazonaws.com/Princess.jpg",
		productLogoAlt: "Princess Bracelet",
		productName: "Princess Bracelet",
		productColor: "pink",
		productRowHeader: "",
		productCardHeader: "",
		productIncludes1: "",
		productIncludes2: "",
		productIncludes3: "",
		productButtonText1: "Fast Checkout",
		productButtonText2: "Add to Cart",
		productPrice: "$2.00"
	},
	{
		productId: "908",
		productLogo: "https://caerwyns-creations.s3.us-west-2.amazonaws.com/Shine_Wrist.jpg",
		productLogoAlt: "Shine Bracelet On Wrist",
		productName: "Shine Bracelet",
		productColor: "red",
		productRowHeader: "",
		productCardHeader: "",
		productIncludes1: "",
		productIncludes2: "",
		productIncludes3: "",
		productButtonText1: "Fast Checkout",
		productButtonText2: "Add to Cart",
		productPrice: "$2.00"
	},
	{
		productId: "909",
		productLogo: "https://caerwyns-creations.s3.us-west-2.amazonaws.com/Surf.jpg",
		productLogoAlt: "Surf Bracelet",
		productName: "Surf Bracelet",
		productColor: "red",
		productRowHeader: "",
		productCardHeader: "",
		productIncludes1: "",
		productIncludes2: "",
		productIncludes3: "",
		productButtonText1: "Fast Checkout",
		productButtonText2: "Add to Cart",
		productPrice: "$2.00"
	}
];

export default productsAndServices;